# https://docs.codecov.com/docs/codecovyml-reference
<<<<<<< HEAD
=======
codecov:
  branch: v2
>>>>>>> v2

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
