name: check-workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'

permissions:
  contents: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      tag-and-release: ${{ steps.changes.outputs.tag-and-release }}
    steps:
      -
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            tag-and-release:
              - '.github/workflows/tag-and-release.yaml'

  release:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.tag-and-release == 'true' }}
    uses: ./.github/workflows/tag-and-release.yaml
