name: pr

on:
  pull_request:
    paths:
      - '.github/workflows/tag-and-release.yaml'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:

  validate-tag-and-release:
    uses: ./.github/workflows/tag-and-release.yaml
