name: tag-and-release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Bump version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          change_path: "app"

      - name: Tag commit
        run: |
          git tag '${{ steps.version.outputs.version_tag }}'
          git push origin '${{ steps.version.outputs.version_tag }}'

      - name: Create release
        run: |
          gh release create '${{ steps.version.outputs.version_tag }}' --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}