name: tag-and-release

on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: write

jobs:

  tag-and-release:
    uses: lucaspopp0/workflows/.github/workflows/tag-and-release.yml@v1
    with:
      change-filters: |
        tagging-workflow:
          - '.github/workflows/tag-and-release.yaml'
        app:
          - 'app/**'
      dry-run: ${{ github.event_name != 'push' }}
