name: tag-and-release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  tag-and-release:
    uses: lucaspopp0/workflows/.github/workflows/tag-and-release.yml@v1
    with:
      change-filters: |
        app:
          - 'app/**'
