name: tag-and-release

on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: write

jobs:

  tag-and-release:
    uses: lucaspopp0/workflows/.github/workflows/tag-and-release.yml@tag-and-release-fix
    with:
      change-filters: |
        app:
          - 'app/**'
