name: unit-test

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-python@v5
        with:
          python-version: 3
      -
        name: Run unit tests
        run: |
          make unit-test
      -
        name: Report code coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          use_oidc: true
